sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
    - PACKAGE=openwrt-ci
    - secure: "O0RaGjWTnxfra87BOE2aoG3Ez7zrkdTGmUJn+cT7FqXsxWWhUEl1Ip676P5c0kbJKyOLg975rr9dFvgJsAOpMFsLDYHAyfTAw3Ov07O+89tTxSsrIlWWUkrAk9iFLbfjDvp8VUnQZS3DKxnR/652hPnQOvbIRD+1qPMd04LEQms="
  matrix:
    - SDK_URL=https://downloads.openwrt.org/releases/17.01.4/targets/ramips/mt7621/lede-sdk-17.01.4-ramips-mt7621_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ccache
install:
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xJf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/lede-sdk-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/src package/$PACKAGE/
script:
- cd $TRAVIS_BUILD_DIR/sdk/lede-sdk-*
- ./scripts/feeds update packages
- ./scripts/feeds install libpthread
- make defconfig
- make
- find $TRAVIS_BUILD_DIR/sdk/lede-sdk-*/bin/
- find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
- cd $TRAVIS_BUILD_DIR/
# - chmod a+x $TRAVIS_BUILD_DIR/deploy.sh
#after_success: $TRAVIS_BUILD_DIR/deploy.sh
#before_deploy:
#  git fetch --tags
#deploy:
#  provider: releases
#  api_key:
#    secure: L5yTlbnfbQ1FWuvI/33nv2vSZNj3fAHPdQ2ORNB5lkrzrzdEDX66kLyygLVpIUm0ZeFhlKAujrXFh5w9Gu9v4E3fuhVBZZ13ZDuopyTWmJDTu/xGbb/10WlsixzXZqAgYwvv6XxPQ6CvEUV01lppS1+787bAbJhpJKUYebiD8H8=
#  skip_cleanup: true
#  file_glob: true
#  file: $TRAVIS_BUILD_DIR/*.ipk
#  on:
#    tags: true
#    all_branches: true