sudo: false
cache:
  directories:
  - cache/
language: c
compiler: gcc
env:
  global:
    - PACKAGE=openwrt-ci
  matrix:
    - SDK_URL=https://downloads.openwrt.org/releases/17.01.4/targets/ramips/mt7620/lede-sdk-17.01.4-ramips-mt7620_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
#    - SDK_URL=https://downloads.openwrt.org/releases/17.01.4/targets/ramips/mt7621/lede-sdk-17.01.4-ramips-mt7621_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
install:
- mkdir -p $TRAVIS_BUILD_DIR/gh-pages
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xJf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/lede-sdk-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/src package/$PACKAGE/
script:
- cd $TRAVIS_BUILD_DIR/sdk/lede-sdk-*
- ./scripts/feeds update
- make defconfig
- sed -i 's/CONFIG_SIGNED_PACKAGES=y/# CONFIG_SIGNED_PACKAGES is not set/g' .config
- make package/$PACKAGE/prepare
- make package/$PACKAGE/compile V=ss
- make package/$PACKAGE/install
- cd ./bin/packages/*/base
- find .
- cp *.ipk $TRAVIS_BUILD_DIR/gh-pages/
- find $TRAVIS_BUILD_DIR/gh-pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: gh-pages
  on:
    branch: master
